cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'heroku'
brew 'hub'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'node'
brew 'openssl'
brew 'python'
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask '1password'
cask 'adium'
cask 'adobe-creative-cloud'
cask 'airvpn'
cask 'appcleaner'
cask 'atom'
# cask 'bitpay'
cask 'chromecast'
cask 'electrum'
cask 'firefox'
cask 'flux'
cask 'github-desktop'
cask 'google-chrome'
cask 'hyper'
cask 'imageoptim'
cask 'ngrok'
cask 'postgres'
cask 'postico'
cask 'resilio-sync'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'telegram'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
cask 'vlc'
cask 'vmware-fusion'
cask 'whatsapp'
